# Generated by Django 4.0 on 2023-05-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationalapp', '0002_course_payment_product_school_schoolcalendar_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='tr_status',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tr_bday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
