# Generated by Django 4.0 on 2023-05-22 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relationalapp', '0003_remove_teacher_tr_status_alter_teacher_tr_bday'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
